@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "URL Shortener Service" as Service
database "Cassandra DB" as DB

== Shorten URL ==
User -> Service : POST /api/urls (long URL)
alt Malformed URL
    Service --> User : 400 Bad Request
else Valid URL
    Service -> DB : Store (shortCode, originalUrl)
    DB --> Service : Acknowledge
    Service --> User : 200 OK + short URL, shortCode
end

== Redirect URL ==
User -> Service : GET /api/urls/{shortCode}
Service -> DB : Gets originalUrl by shortCode
alt Not Found
    DB --> Service : null
    Service --> User : 404 Not Found
else Found
    DB --> Service : longURL
    Service --> User : 302 Found + Redirect to longURL
end

@enduml